# RAM addresses

# 1600 changes whenever entering battle, so ignore it for now
ALL_FLAG_START = 0x1601
ALL_FLAG_END = 0x1649
ALL_FLAG_LEN = ALL_FLAG_END - ALL_FLAG_START

CHEST_FLAG_START = 0x1620
CHEST_FLAG_END = 0x163a

INVENTORY_START = 0x16ea
INVENTORY_END = 0x171a
INVENTORY_LENGTH = INVENTORY_END - INVENTORY_START

GOLD_START = 0x16a4
GOLD_LENGTH = 4

HERO_MAX_HP_START = 0x16b4
HERO_MAX_HP_LENGTH = 2

# ROM addresses

"""
possibly useful ROM addresses

~2D30   initial RAM:1600 block?
~69E4   item names, enemy names, npc names
"""

ROM_INTERNATIONAL_NAME = 0x150
ROM_VERSION = 0x18c


LAB_L1_CHEST_CONTENTS = 0x84c6
LAB_L2_CHEST_CONTENTS = 0x84d3
LAB_L3_CHEST_CONTENTS = 0x84e1
LAB_L4_CHEST_CONTENTS = 0x84ec
LAB_L5_CHEST_CONTENTS = 0x84fa
WIS_L1_CHEST_CONTENTS = 0x8508
WIS_L2_CHEST_CONTENTS = 0x8508
UNUSED_CHEST_CONTENTS = 0x8517
TRUTH_CHEST_CONTENTS = 0x8518
STRENGTH_L1_CHEST_CONTENTS = 0x8528
SHARED_L2_CHEST_CONTENTS = 0x8537
COURAGE_L1_CHEST_CONTENTS = 0x8539
CHEST_CONTENTS_BY_FLOOR = [
    LAB_L1_CHEST_CONTENTS,
    LAB_L2_CHEST_CONTENTS,
    LAB_L3_CHEST_CONTENTS,
    LAB_L4_CHEST_CONTENTS,
    LAB_L5_CHEST_CONTENTS,
    WIS_L1_CHEST_CONTENTS,
    WIS_L2_CHEST_CONTENTS,
    UNUSED_CHEST_CONTENTS,
    TRUTH_CHEST_CONTENTS,
    STRENGTH_L1_CHEST_CONTENTS,
    SHARED_L2_CHEST_CONTENTS,
    COURAGE_L1_CHEST_CONTENTS,
]

NAME_SPACE = 0xfff30
NAME_SPACE_LEN = 0xd0
