from enum import IntEnum, IntFlag
from operator import attrgetter

from BaseClasses import ItemClassification

from .constants import jet_scooter_flag, spaceship_flag
from .Data import item_name as i
from .Data import tech_id
from .Data.types import EquipSlot as S
from .laglib import IntSpan
from .messages import translate_message


class ItemType(IntEnum):
    Garbage = 0
    Item = 1
    Money = 2
    Flag = 3
    FlagAsItem = 4


class ItemFlags(IntFlag):
    NONE = 0
    Map = 0x8
    Battle = 0x10
    Store = 0x20
    RevertToAttack = 0x40
    Sell = 0x80


class ItemData:
    id: int
    type: ItemType
    name: str
    classification: ItemClassification
    code: int | None = None
    slot: S = S.NONE
    meseta: int | None = None
    ram_flag: IntSpan | None = None
    ram_value: int = 1
    price: int = 0
    flags: ItemFlags = ItemFlags.NONE
    at: int = 0
    df: int = 0
    ag: int = 0
    use_tech: int = 0

    def __init__(
        self,
        id: int,
        type: ItemType,
        name: str,
        classification: ItemClassification,
        code: int | None = None,
        slot: S = S.NONE,
        meseta: int | None = None,
        ram_flag: IntSpan | None = None,
        ram_value: int = 1,
        price: int = 0,
        flags: ItemFlags = ItemFlags.NONE,
        at: int = 0,
        df: int = 0,
        ag: int = 0,
        use_tech: int = 0,
    ):
        self.id = id
        self.type = type
        self.name = name
        self.classification = classification
        self.code = code
        self.slot = slot
        self.meseta = meseta
        self.ram_flag = ram_flag
        self.ram_value = ram_value
        self.price = price
        self.flags = flags
        self.at = at
        self.df = df
        self.ag = ag  # TODO write this to ROM
        self.use_tech = use_tech

    def __repr__(self) -> str:
        return f"{self.name}: cl={self.classification} code={self.code}"

    @property
    def code_as_int(self):
        if self.code is None:
            return -1
        return self.code

    def get_chest_bytes(self):
        raw: int | None = None
        if self.name == i.Garbage:
            raw = 0
        elif self.meseta is not None:
            if self.meseta > 0x7FFF:
                raise Exception(f"meseta amount {self.meseta} too high")
            raw = self.meseta
        elif self.code is not None:
            raw = self.code | 0x8000
        if raw is None:
            raise Exception(f"Item {self.name} cannot be placed in chest!")
        return raw.to_bytes(2, "big")

    def get_data_bytes(self, char_mask: int):
        if len(self.name) > 10:
            raise Exception(f"item {self.name} has name too long (max 10)")
        if self.price > 0xFFFF:
            raise Exception(f"item {self.name} has price over 65536")
        if self.use_tech and ItemFlags.Battle not in self.flags:
            raise Exception(f"item {self.name} has a tech but not ItemFlags.Battle")
        if self.use_tech == 0 and ItemFlags.Battle in self.flags:
            raise Exception(f"item {self.name} has ItemFlags.Battle but no tech")
        name = self.name
        padding = 10 - len(name)
        if padding > 0:
            padding -= 1
            name += "<END>"
        if padding > 0:
            name += " " * padding
        return (
            translate_message(name)
            + self.price.to_bytes(2, "big")
            + bytes([self.slot.value | self.flags.value, char_mask, self.at, self.df])
        )


unused_items = [
    ItemData(452_1_000, ItemType.Item, "", ItemClassification.filler, 0),
    ItemData(
        452_1_126,
        ItemType.Item,
        "T",
        ItemClassification.filler,
        0x7E,
        flags=ItemFlags.Map | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=62000,
    ),
    ItemData(
        452_1_127,
        ItemType.Item,
        "H",
        ItemClassification.filler,
        0x7F,
        flags=ItemFlags.Map | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=46000,
    ),
]

key_items = [
    ItemData(
        452_1_001,
        ItemType.Item,
        i.SmallKey,
        ItemClassification.progression,
        0x1,
        flags=ItemFlags.Map | ItemFlags.Store,
    ),
    ItemData(
        452_1_002,
        ItemType.Item,
        i.Dynamite,
        ItemClassification.progression,
        0x2,
        flags=ItemFlags.Map | ItemFlags.RevertToAttack,
    ),
    ItemData(
        452_1_003,
        ItemType.Item,
        i.KeyTube,
        ItemClassification.progression,
        0x3,
        flags=ItemFlags.Map | ItemFlags.Store,
    ),
    ItemData(
        452_1_004,
        ItemType.Item,
        i.MarueraGum,
        ItemClassification.progression,
        0x4,
        flags=ItemFlags.Map | ItemFlags.Store,
    ),
    ItemData(
        452_1_005,
        ItemType.Item,
        i.GreenCard,
        ItemClassification.progression,
        0x5,
        flags=ItemFlags.Map | ItemFlags.Store,
    ),
    ItemData(
        452_1_006,
        ItemType.Item,
        i.BlueCard,
        ItemClassification.progression,
        0x6,
        flags=ItemFlags.Map | ItemFlags.Store,
    ),
    ItemData(
        452_1_007,
        ItemType.Item,
        i.YellowCard,
        ItemClassification.progression,
        0x7,
        flags=ItemFlags.Map | ItemFlags.Store,
    ),
    ItemData(
        452_1_008,
        ItemType.Item,
        i.RedCard,
        ItemClassification.progression,
        0x8,
        flags=ItemFlags.Map | ItemFlags.Store,
    ),
    ItemData(452_1_009, ItemType.Item, i.Letter, ItemClassification.progression, 0x9, flags=ItemFlags.Map),
    ItemData(452_1_010, ItemType.Item, i.Recorder, ItemClassification.progression, 0xA, flags=ItemFlags.Map),
    ItemData(
        452_1_011,
        ItemType.Item,
        i.MarueraLeaf,
        ItemClassification.progression,
        0xB,
        flags=ItemFlags.Map | ItemFlags.Store,
    ),
    ItemData(452_1_013, ItemType.Item, i.Prism, ItemClassification.progression, 0xD, flags=ItemFlags.Map),
    ItemData(
        452_1_039,
        ItemType.Item,
        i.NeiMet,
        ItemClassification.progression,
        0x27,
        S.Head,
        flags=ItemFlags.Store,
        df=50,
    ),
    ItemData(
        452_1_040,
        ItemType.Item,
        i.NeiCrown,
        ItemClassification.progression,
        0x28,
        S.Head,
        flags=ItemFlags.Store,
        df=48,
    ),
    ItemData(
        452_1_061,
        ItemType.Item,
        i.NeiArmor,
        ItemClassification.progression,
        0x3D,
        S.Body,
        flags=ItemFlags.Store,
        df=95,
    ),
    ItemData(
        452_1_062,
        ItemType.Item,
        i.NeiCape,
        ItemClassification.progression,
        0x3E,
        S.Body,
        flags=ItemFlags.Store,
        df=88,
    ),
    ItemData(
        452_1_084,
        ItemType.Item,
        i.NeiShield,
        ItemClassification.progression,
        0x54,
        S.OneHand,
        flags=ItemFlags.Store,
        df=95,
    ),
    ItemData(
        452_1_085,
        ItemType.Item,
        i.NeiEmel,
        ItemClassification.progression,
        0x55,
        S.OneHand,
        flags=ItemFlags.Store,
        df=118,
    ),
    # this isn't actually needed, but good luck beating Dark Force without it
    ItemData(
        452_1_108,
        ItemType.Item,
        i.NeiSword,
        ItemClassification.progression,
        0x6C,
        S.TwoHand,
        flags=ItemFlags.Map | ItemFlags.Store,
        at=75,
        df=24,
    ),
    ItemData(
        452_1_109,
        ItemType.Item,
        i.NeiSlasher,
        ItemClassification.progression,
        0x6D,
        S.OneHand,
        flags=ItemFlags.Store,
        at=60,
    ),
    ItemData(
        452_1_122,
        ItemType.Item,
        i.NeiShot,
        ItemClassification.progression,
        0x7A,
        S.TwoHand,
        flags=ItemFlags.Store,
        at=60,
    ),
    ItemData(452_1_124, ItemType.Item, i.Teim, ItemClassification.progression, 0x7C, flags=ItemFlags.Map),
]

flag_items = [
    ItemData(452_9_000, ItemType.Flag, i.MusikFlag, ItemClassification.progression),
    ItemData(
        452_9_001,
        ItemType.FlagAsItem,
        i.JetScooterFlag,
        ItemClassification.progression,
        0xE1,
        ram_flag=jet_scooter_flag,
        ram_value=2,
    ),
    ItemData(452_9_002, ItemType.Flag, i.NeifirstFlag, ItemClassification.progression),
    ItemData(452_9_003, ItemType.Flag, i.RedDamFlag, ItemClassification.progression),
    ItemData(452_9_004, ItemType.Flag, i.YellowDamFlag, ItemClassification.progression),
    ItemData(452_9_005, ItemType.Flag, i.BlueDamFlag, ItemClassification.progression),
    ItemData(452_9_006, ItemType.Flag, i.GreenDamFlag, ItemClassification.progression),
    ItemData(
        452_9_007,
        ItemType.FlagAsItem,
        i.SpaceshipFlag,
        ItemClassification.progression,
        0xE2,
        ram_flag=spaceship_flag,
    ),
    ItemData(452_9_008, ItemType.Flag, i.WinTheGameFlag, ItemClassification.progression),
]


required_items = key_items + flag_items


unique_useful_items = [
    ItemData(
        452_1_042,
        ItemType.Item,
        i.MogicCap,
        ItemClassification.useful,
        0x2A,
        S.Head,
        flags=ItemFlags.Store,
        df=2,
    ),
    ItemData(
        452_1_125,
        ItemType.Item,
        i.Visiphone,
        ItemClassification.useful,
        0x7D,
        flags=ItemFlags.Map | ItemFlags.Store | ItemFlags.Sell,
        price=3000,
    ),
]

equipment_items = [
    ItemData(
        452_1_023,
        ItemType.Item,
        i.Headgear,
        ItemClassification.useful,
        0x17,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=3,
        price=120,
    ),
    ItemData(
        452_1_024,
        ItemType.Item,
        i.Ribbon,
        ItemClassification.useful,
        0x18,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=3,
        price=80,
    ),
    ItemData(
        452_1_025,
        ItemType.Item,
        i.FiberGear,
        ItemClassification.useful,
        0x19,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=8,
        price=430,
    ),
    ItemData(
        452_1_026,
        ItemType.Item,
        i.SilRibbon,
        ItemClassification.useful,
        0x1A,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=12,
        price=380,
    ),
    ItemData(
        452_1_027,
        ItemType.Item,
        i.SilCrown,
        ItemClassification.useful,
        0x1B,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=14,
        price=470,
    ),
    ItemData(
        452_1_028,
        ItemType.Item,
        i.TitaniGear,
        ItemClassification.useful,
        0x1C,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=14,
        price=1400,
    ),
    ItemData(
        452_1_029,
        ItemType.Item,
        i.TitaniMet,
        ItemClassification.useful,
        0x1D,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=16,
        price=3700,
    ),
    ItemData(
        452_1_030,
        ItemType.Item,
        i.JwlCrown,
        ItemClassification.useful,
        0x1E,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=17,
        price=4600,
    ),
    ItemData(
        452_1_031,
        ItemType.Item,
        i.JwlRibbon,
        ItemClassification.useful,
        0x1F,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=21,
        price=4700,
    ),
    ItemData(
        452_1_032,
        ItemType.Item,
        i.CresceGear,
        ItemClassification.useful,
        0x20,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=14,
        price=280,
        use_tech=tech_id.GIRES,
    ),
    ItemData(
        452_1_033,
        ItemType.Item,
        i.SnowCrown,
        ItemClassification.useful,
        0x21,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=17,
        price=490,
        use_tech=tech_id.DEBAN,
    ),
    ItemData(
        452_1_034,
        ItemType.Item,
        i.WindScarf,
        ItemClassification.useful,
        0x22,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=17,
        price=120,
        use_tech=tech_id.ZAN,
    ),
    ItemData(
        452_1_035,
        ItemType.Item,
        i.ColorScarf,
        ItemClassification.useful,
        0x23,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=17,
        price=130,
        use_tech=tech_id.SANER,
    ),
    ItemData(
        452_1_036,
        ItemType.Item,
        i.StormGear,
        ItemClassification.useful,
        0x24,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=16,
        price=630,
        use_tech=tech_id.GIZAN,
    ),
    ItemData(
        452_1_037,
        ItemType.Item,
        i.Laconigear,
        ItemClassification.useful,
        0x25,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=27,
        price=28000,
    ),
    ItemData(
        452_1_038,
        ItemType.Item,
        i.LaconiaMet,
        ItemClassification.useful,
        0x26,
        S.Head,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=29,
        price=29000,
    ),
    ItemData(
        452_1_043,
        ItemType.Item,
        i.CarbonSuit,
        ItemClassification.useful,
        0x2B,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=4,
        price=128,
    ),
    ItemData(
        452_1_044,
        ItemType.Item,
        i.CarbonVest,
        ItemClassification.useful,
        0x2C,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=4,
        price=120,
    ),
    ItemData(
        452_1_045,
        ItemType.Item,
        i.FiberCoat,
        ItemClassification.useful,
        0x2D,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=8,
        price=300,
    ),
    ItemData(
        452_1_046,
        ItemType.Item,
        i.FiberCape,
        ItemClassification.useful,
        0x2E,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=8,
        price=420,
    ),
    ItemData(
        452_1_047,
        ItemType.Item,
        i.FiberVest,
        ItemClassification.useful,
        0x2F,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=6,
        price=280,
    ),
    ItemData(
        452_1_048,
        ItemType.Item,
        i.TtnmArmor,
        ItemClassification.useful,
        0x30,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=24,
        price=5600,
    ),
    ItemData(
        452_1_049,
        ItemType.Item,
        i.TtnmCape,
        ItemClassification.useful,
        0x31,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=28,
        price=6300,
    ),
    ItemData(
        452_1_050,
        ItemType.Item,
        i.TtnmChest,
        ItemClassification.useful,
        0x32,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=21,
        price=5400,
    ),
    ItemData(
        452_1_051,
        ItemType.Item,
        i.CrmcArmor,
        ItemClassification.useful,
        0x33,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=48,
        price=11700,
    ),
    ItemData(
        452_1_052,
        ItemType.Item,
        i.CrmcCape,
        ItemClassification.useful,
        0x34,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=56,
        price=12400,
    ),
    ItemData(
        452_1_053,
        ItemType.Item,
        i.CrmcChest,
        ItemClassification.useful,
        0x35,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=46,
        price=10000,
    ),
    ItemData(
        452_1_054,
        ItemType.Item,
        i.AmberRobe,
        ItemClassification.useful,
        0x36,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=20,
        price=170,
        use_tech=tech_id.GIRES,
    ),
    ItemData(
        452_1_055,
        ItemType.Item,
        i.Crystanish,
        ItemClassification.useful,
        0x37,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=60,
        price=630,
        use_tech=tech_id.GRA,
    ),
    ItemData(
        452_1_056,
        ItemType.Item,
        i.CrystCape,
        ItemClassification.useful,
        0x38,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=62,
        price=840,
        use_tech=tech_id.GRA,
    ),
    ItemData(
        452_1_057,
        ItemType.Item,
        i.CrystChest,
        ItemClassification.useful,
        0x39,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=60,
        price=670,
        use_tech=tech_id.GRA,
    ),
    ItemData(
        452_1_058,
        ItemType.Item,
        i.Laconinish,
        ItemClassification.useful,
        0x3A,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=65,
        price=35000,
    ),
    ItemData(
        452_1_059,
        ItemType.Item,
        i.LaconCape,
        ItemClassification.useful,
        0x3B,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=70,
        price=36000,
    ),
    ItemData(
        452_1_060,
        ItemType.Item,
        i.LaconChest,
        ItemClassification.useful,
        0x3C,
        S.Body,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=80,
        price=28000,
    ),
    ItemData(
        452_1_063,
        ItemType.Item,
        i.Shoes,
        ItemClassification.useful,
        0x3F,
        S.Feet,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=3,
        ag=2,
        price=240,
    ),
    ItemData(
        452_1_064,
        ItemType.Item,
        i.Sandals,
        ItemClassification.useful,
        0x40,
        S.Feet,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=3,
        ag=3,
        price=180,
    ),
    ItemData(
        452_1_065,
        ItemType.Item,
        i.Boots,
        ItemClassification.useful,
        0x41,
        S.Feet,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=7,
        ag=3,
        price=1000,
    ),
    ItemData(
        452_1_066,
        ItemType.Item,
        i.KnifeBoots,
        ItemClassification.useful,
        0x42,
        S.Feet,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=7,
        df=7,
        ag=5,
        price=4200,
    ),
    ItemData(
        452_1_067,
        ItemType.Item,
        i.LongBoots,
        ItemClassification.useful,
        0x43,
        S.Feet,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=5,
        df=7,
        ag=7,
        price=6800,
    ),
    ItemData(
        452_1_068,
        ItemType.Item,
        i.HirzaBoots,
        ItemClassification.useful,
        0x44,
        S.Feet,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=7,
        ag=7,
        price=9800,
    ),
    ItemData(
        452_1_069,
        ItemType.Item,
        i.ShuneBoots,
        ItemClassification.useful,
        0x45,
        S.Feet,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=7,
        ag=10,
        price=7500,
    ),
    ItemData(
        452_1_070,
        ItemType.Item,
        i.GardaBoots,
        ItemClassification.useful,
        0x46,
        S.Feet,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=15,
        ag=8,
        price=12400,
    ),
    ItemData(
        452_1_071,
        ItemType.Item,
        i.CrbnShield,
        ItemClassification.useful,
        0x47,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=8,
        price=540,
    ),
    ItemData(
        452_1_072,
        ItemType.Item,
        i.CrbnEmel,
        ItemClassification.useful,
        0x48,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=7,
        price=420,
    ),
    ItemData(
        452_1_073,
        ItemType.Item,
        i.FibrShild,
        ItemClassification.useful,
        0x49,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=15,
        price=1200,
    ),
    ItemData(
        452_1_074,
        ItemType.Item,
        i.FiberEmel,
        ItemClassification.useful,
        0x4A,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=17,
        price=1360,
    ),
    ItemData(
        452_1_075,
        ItemType.Item,
        i.MirShield,
        ItemClassification.useful,
        0x4B,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=32,
        price=4800,
    ),
    ItemData(
        452_1_076,
        ItemType.Item,
        i.MirEmel,
        ItemClassification.useful,
        0x4C,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=30,
        price=5120,
    ),
    ItemData(
        452_1_077,
        ItemType.Item,
        i.CerShield,
        ItemClassification.useful,
        0x4D,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=39,
        price=8300,
    ),
    ItemData(
        452_1_078,
        ItemType.Item,
        i.CerEmel,
        ItemClassification.useful,
        0x4E,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=40,
        price=9700,
    ),
    ItemData(
        452_1_079,
        ItemType.Item,
        i.Aegis,
        ItemClassification.useful,
        0x4F,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=32,
        price=1200,
        use_tech=tech_id.GIRES,
    ),
    ItemData(
        452_1_080,
        ItemType.Item,
        i.GrSleeves,
        ItemClassification.useful,
        0x50,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=63,
        price=840,
        use_tech=tech_id.SHINB,
    ),
    ItemData(
        452_1_081,
        ItemType.Item,
        i.TruthSlvs,
        ItemClassification.useful,
        0x51,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        df=59,
        price=720,
        use_tech=tech_id.GIRES,
    ),
    ItemData(
        452_1_082,
        ItemType.Item,
        i.LaconEmel,
        ItemClassification.useful,
        0x52,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=68,
        price=12000,
    ),
    ItemData(
        452_1_083,
        ItemType.Item,
        i.LacShield,
        ItemClassification.useful,
        0x53,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        df=85,
        price=13000,
    ),
    ItemData(
        452_1_086,
        ItemType.Item,
        i.Knife,
        ItemClassification.useful,
        0x56,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=5,
        price=100,
    ),
    ItemData(
        452_1_087,
        ItemType.Item,
        i.Dagger,
        ItemClassification.useful,
        0x57,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=8,
        df=1,
        price=200,
    ),
    ItemData(
        452_1_088,
        ItemType.Item,
        i.Scalpel,
        ItemClassification.useful,
        0x58,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=7,
        price=180,
    ),
    ItemData(
        452_1_089,
        ItemType.Item,
        i.SteelBar,
        ItemClassification.useful,
        0x59,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=7,
        df=2,
        price=80,
    ),
    ItemData(
        452_1_090,
        ItemType.Item,
        i.Boomerang,
        ItemClassification.useful,
        0x5A,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=12,
        price=480,
    ),
    ItemData(
        452_1_091,
        ItemType.Item,
        i.Slasher,
        ItemClassification.useful,
        0x5B,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=17,
        price=2000,
    ),
    ItemData(
        452_1_092,
        ItemType.Item,
        i.Sword,
        ItemClassification.useful,
        0x5C,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=18,
        df=4,
        price=1200,
    ),
    ItemData(
        452_1_093,
        ItemType.Item,
        i.Whip,
        ItemClassification.useful,
        0x5D,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=20,
        df=2,
        price=1400,
    ),
    ItemData(
        452_1_094,
        ItemType.Item,
        i.CeramSwrd,
        ItemClassification.useful,
        0x5E,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=30,
        df=5,
        price=3200,
    ),
    ItemData(
        452_1_095,
        ItemType.Item,
        i.CeramKnfe,
        ItemClassification.useful,
        0x5F,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=20,
        df=3,
        price=2800,
    ),
    ItemData(
        452_1_096,
        ItemType.Item,
        i.CeramBar,
        ItemClassification.useful,
        0x60,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=27,
        df=2,
        price=1200,
    ),
    ItemData(
        452_1_097,
        ItemType.Item,
        i.LasrSlshr,
        ItemClassification.useful,
        0x61,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=30,
        price=6700,
    ),
    ItemData(
        452_1_098,
        ItemType.Item,
        i.LasrSword,
        ItemClassification.useful,
        0x62,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=50,
        df=9,
        price=5400,
    ),
    ItemData(
        452_1_099,
        ItemType.Item,
        i.LaserBar,
        ItemClassification.useful,
        0x63,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=38,
        df=3,
        price=3100,
    ),
    ItemData(
        452_1_100,
        ItemType.Item,
        i.LaserKnfe,
        ItemClassification.useful,
        0x64,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=28,
        df=5,
        price=4400,
    ),
    ItemData(
        452_1_101,
        ItemType.Item,
        i.SwdOfAng,
        ItemClassification.useful,
        0x65,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=58,
        price=280,
    ),
    ItemData(
        452_1_102,
        ItemType.Item,
        i.FireSlshr,
        ItemClassification.useful,
        0x66,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=36,
        price=340,
    ),
    ItemData(
        452_1_103,
        ItemType.Item,
        i.FireStaff,
        ItemClassification.useful,
        0x67,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell | ItemFlags.Battle,
        at=32,
        df=11,
        price=670,
        use_tech=tech_id.FOI,
    ),
    ItemData(
        452_1_104,
        ItemType.Item,
        i.LacnMace,
        ItemClassification.useful,
        0x68,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=40,
        df=8,
        price=16800,
    ),
    ItemData(
        452_1_105,
        ItemType.Item,
        i.LacDagger,
        ItemClassification.useful,
        0x69,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=4,
        df=22,
        price=18400,
    ),
    ItemData(
        452_1_106,
        ItemType.Item,
        i.ACSlashr,
        ItemClassification.useful,
        0x6A,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=42,
        price=24000,
    ),
    ItemData(
        452_1_107,
        ItemType.Item,
        i.LacSword,
        ItemClassification.useful,
        0x6B,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=62,
        df=7,
        price=22000,
    ),
    ItemData(
        452_1_110,
        ItemType.Item,
        i.BowGun,
        ItemClassification.useful,
        0x6E,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=8,
        price=300,
    ),
    ItemData(
        452_1_111,
        ItemType.Item,
        i.SonicGun,
        ItemClassification.useful,
        0x6F,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=17,
        price=640,
    ),
    ItemData(
        452_1_112,
        ItemType.Item,
        i.Shotgun,
        ItemClassification.useful,
        0x70,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=10,
        price=800,
    ),
    ItemData(
        452_1_113,
        ItemType.Item,
        i.SilentShot,
        ItemClassification.useful,
        0x71,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=10,
        price=920,
    ),
    ItemData(
        452_1_114,
        ItemType.Item,
        i.PoisonShot,
        ItemClassification.useful,
        0x72,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=15,
        price=1700,
    ),
    ItemData(
        452_1_115,
        ItemType.Item,
        i.AcidShot,
        ItemClassification.useful,
        0x73,
        S.OneHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=25,
        price=4800,
    ),
    ItemData(
        452_1_116,
        ItemType.Item,
        i.Cannon,
        ItemClassification.useful,
        0x74,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=18,
        price=2200,
    ),
    ItemData(
        452_1_117,
        ItemType.Item,
        i.Vulcan,
        ItemClassification.useful,
        0x75,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=28,
        price=12600,
    ),
    ItemData(
        452_1_118,
        ItemType.Item,
        i.LaserShot,
        ItemClassification.useful,
        0x76,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=20,
        price=6200,
    ),
    ItemData(
        452_1_119,
        ItemType.Item,
        i.LsrCannon,
        ItemClassification.useful,
        0x77,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=30,
        price=20000,
    ),
    ItemData(
        452_1_120,
        ItemType.Item,
        i.PlsCannon,
        ItemClassification.useful,
        0x78,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=35,
        price=32000,
    ),
    ItemData(
        452_1_121,
        ItemType.Item,
        i.PulseVlcn,
        ItemClassification.useful,
        0x79,
        S.TwoHand,
        flags=ItemFlags.Store | ItemFlags.Sell,
        at=38,
        price=48000,
    ),
]

useful_items = unique_useful_items + equipment_items
useful_item_names = [item.name for item in useful_items]

consumable_items = [
    ItemData(
        452_1_014,
        ItemType.Item,
        i.Telepipe,
        ItemClassification.filler,
        0xE,
        flags=ItemFlags.Map | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=130,
    ),
    ItemData(
        452_1_015,
        ItemType.Item,
        i.Escapipe,
        ItemClassification.filler,
        0xF,
        flags=ItemFlags.Map | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=70,
    ),
    ItemData(
        452_1_016,
        ItemType.Item,
        i.Hidapipe,
        ItemClassification.filler,
        0x10,
        flags=ItemFlags.Map | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=280,
    ),
    ItemData(
        452_1_017,
        ItemType.Item,
        i.Monomate,
        ItemClassification.filler,
        0x11,
        flags=ItemFlags.Map | ItemFlags.Battle | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=20,
        use_tech=tech_id.RES,
    ),
    ItemData(
        452_1_018,
        ItemType.Item,
        i.Dimate,
        ItemClassification.filler,
        0x12,
        flags=ItemFlags.Map | ItemFlags.Battle | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=50,
        use_tech=tech_id.GIRES,
    ),
    ItemData(
        452_1_019,
        ItemType.Item,
        i.Trimate,
        ItemClassification.filler,
        0x13,
        flags=ItemFlags.Map | ItemFlags.Battle | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=160,
        use_tech=tech_id.NARES,
    ),
    ItemData(
        452_1_020,
        ItemType.Item,
        i.Antidote,
        ItemClassification.filler,
        0x14,
        flags=ItemFlags.Map | ItemFlags.Battle | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=10,
        use_tech=tech_id.ANTI,
    ),
    ItemData(
        452_1_021,
        ItemType.Item,
        i.StarMist,
        ItemClassification.filler,
        0x15,
        flags=ItemFlags.Map | ItemFlags.Battle | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=1000,
        use_tech=tech_id.NASAR,
    ),
    ItemData(
        452_1_022,
        ItemType.Item,
        i.MoonDew,
        ItemClassification.filler,
        0x16,
        flags=ItemFlags.Map | ItemFlags.Battle | ItemFlags.Store | ItemFlags.RevertToAttack | ItemFlags.Sell,
        price=12000,
        use_tech=tech_id.REVER,
    ),
]

junk_items = [
    ItemData(
        452_1_041,
        ItemType.Item,
        i.MagicCap,
        ItemClassification.filler,
        0x29,
        S.Head,
        flags=ItemFlags.Store,
        df=2,
    ),
    ItemData(452_1_123, ItemType.Item, i.PrsnClths, ItemClassification.filler, 0x7B, S.Body, df=2, price=100),
    ItemData(452_2_000, ItemType.Garbage, i.Garbage, ItemClassification.filler),
]


dangerous_items = [
    # not sure if this is _really_ bad, but it can't be good
    ItemData(452_1_012, ItemType.Item, i.PlasmaRing, ItemClassification.filler, 0xC, flags=ItemFlags.Map),
]

meseta_items = [
    ItemData(452_2_001, ItemType.Money, i.meseta(20), ItemClassification.filler, meseta=20),
    ItemData(452_2_002, ItemType.Money, i.meseta(40), ItemClassification.filler, meseta=40),
    ItemData(452_2_003, ItemType.Money, i.meseta(60), ItemClassification.filler, meseta=60),
    ItemData(452_2_004, ItemType.Money, i.meseta(100), ItemClassification.filler, meseta=100),
    ItemData(452_2_005, ItemType.Money, i.meseta(150), ItemClassification.filler, meseta=150),
    ItemData(452_2_006, ItemType.Money, i.meseta(200), ItemClassification.filler, meseta=200),
    ItemData(452_2_007, ItemType.Money, i.meseta(5600), ItemClassification.filler, meseta=5600),
    ItemData(452_2_008, ItemType.Money, i.meseta(6400), ItemClassification.filler, meseta=6400),
    ItemData(452_2_009, ItemType.Money, i.meseta(7800), ItemClassification.filler, meseta=7800),
    ItemData(452_2_010, ItemType.Money, i.meseta(8600), ItemClassification.filler, meseta=8600),
    ItemData(452_2_011, ItemType.Money, i.meseta(12000), ItemClassification.filler, meseta=12000),
    ItemData(452_2_012, ItemType.Money, i.meseta(15000), ItemClassification.filler, meseta=15000),
    ItemData(452_2_013, ItemType.Money, i.meseta(18000), ItemClassification.filler, meseta=18000),
]

filler_items = consumable_items + junk_items + meseta_items
filler_item_names = [item.name for item in filler_items]

item_name_groups = {
    "Key Items": {item.name for item in key_items},
    "Unique and Useful": {item.name for item in unique_useful_items},
    "Equipment": {item.name for item in equipment_items},
    "Consumables": {item.name for item in consumable_items},
    "Junk": {item.name for item in junk_items},
    "Quest Flags": {item.name for item in flag_items},
}

all_items = required_items + useful_items + filler_items + dangerous_items
items_by_name = {item.name: item for item in all_items}
items_by_id = {item.id: item for item in all_items}

items_with_codes = sorted(
    [item for item in all_items + unused_items if item.type == ItemType.Item and item.code is not None],
    key=attrgetter("code_as_int"),
)
