# key item codes

RoyalTiara = "Royal Tiara"
DwarfKey = "Dwarf's Key"
OrbOfTruth = "Orb of Truth"
FalseIdol = "False Idol"
RuneKey = "Rune Key"
MysticRope = "Mystic Rope"
CellKey = "Cell Key"

# other stuff given by court

VialOfTears = "Vial of Tears"
Medallion = "Medallion"
MagicRing = "Magic Ring"

# monsters in a box

ChestBeak = "Chest Beak"
Ghost = "Ghost"
HandEater = "Hand Eater"

# other physical items

BronzeKnife = "Bronze Knife"
ShortSword = "Short Sword"
Sword = "Sword"
Longsword = "Longsword"
Broadsword = "Broadsword"
FireSword = "Fire Sword"
StormSword = "Storm Sword"
LightBlade = "Light Blade"
DarkBlade = "Dark Blade"
DreamBlade = "Dream Blade"
BronzeSaber = "Bronze Saber"
SteelSaber = "Steel Saber"
BattleHammer = "Battle Hammer"
MithrilAxe = "Mithril Axe"
IceSaber = "Ice Saber"
DarkScimitar = "Dark Scimitar"
ShortAxe = "Short Axe"
BattleAxe = "Battle Axe"
DoubleAxe = "Double Axe"
GreatAxe = "Great Axe"
MithrilSword = "Mithril Sword"
WoodStaff = "Wood Staff"
Flail = "Flail"
Morningstar = "Morningstar"
FireStaff = "Fire Staff"
IceStaff = "Ice Staff"
MercyStaff = "Mercy Staff"
Endurostaff = "Endurostaff"
DoomStaff = "Doom Staff"
MithrilRod = "Mithril Rod"
WoodenClub = "Wooden Club"
WarHammer = "War Hammer"
BronzeLance = "Bronze Lance"
IronLance = "Iron Lance"
SteelLance = "Steel Lance"
ShortSpear = "Short Spear"
LongSpear = "Long Spear"
Bullwhip = "Bullwhip"
ThornWhip = "Thorn Whip"
SteelWhip = "Steel Whip"
HexWhip = "Hex Whip"
GreatFlail = "Great Flail"
SuperFlail = "Super Flail"
DoomBlade = "Doom Blade"
WoodShield = "Wood Shield"
DarkArmor = "Dark Armor"
FrostArmor = "Frost Armor"
ThunderArmor = "Thunder Armor"
SunArmor = "Sun Armor"
CottonRobe = "Cotton Robe"
WovenRobe = "Woven Robe"
FurRobe = "Fur Robe"
WornRobe = "Worn Robe"
StrawRobe = "Straw Robe"
HempRobe = "Hemp Robe"
LeatherRobe = "Leather Robe"
LightRobe = "Light Robe"
MagicRobe = "Magic Robe"
DarkRobe = "Dark Robe"
LeatherArmor = "Leather Armor"
Chainmail = "Chainmail"
Breastplate = "Breastplate"
BronzeArmor = "Bronze Armor"
IronArmor = "Iron Armor"
SteelArmor = "Steel Armor"
MithrilArmor = "Mithril Armor"
LightArmor = "Light Armor"
BronzeShield = "Bronze Shield"
IronShield = "Iron Shield"
SteelShield = "Steel Shield"
LeatherShield = "Leather Shield"
LightShield = "Light Shield"
DarkShield = "Dark Shield"
MithrilShield = "Mithril Shield"
ElvenHood = "Elven Hood"
ClothHood = "Cloth Hood"
WovenHood = "Woven Hood"
FurHood = "Fur Hood"
MagicHood = "Magic Hood"
DarkHood = "Dark Hood"
MithrilHood = "Mithril Hood"
LeatherHelm = "Leather Helm"
BronzeHelm = "Bronze Helm"
IronHelm = "Iron Helm"
SteelHelm = "Steel Helm"
LightHelm = "Light Helm"
DarkHelm = "Dark Helm"
MithrilHelm = "Mithril Helm"
MagicShield = "Magic Shield"
MagicMail = "Magic Mail"
ForbiddenBox = "Forbidden Box"
MainGauche = "Main Gauche"
Madu = "Madu"
EarthHammer = "Earth Hammer"
ShockBox = "Shock Box"
OgreFlute = "Ogre Flute"
BlackBox = "Black Box"
Gauntlet = "Gauntlet"
DemonStaff = "Demon Staff"
MithrilOre = "Mithril Ore"
DarkBlock = "Dark Block"
Herb = "Herb"
Depoison = "Depoison"
AngelFeather = "Angel Feather"
WisdomSeed = "Wisdom Seed"
Tamayoshi = "Tamayoshi"
HealRing = "Heal Ring"
BarrierRing = "Barrier Ring"
MagicMirror = "Magic Mirror"
HerbWater = "Herb Water"
HolyWater = "Holy Water"
HealerFruit = "Healer Fruit"
SmellingSalts = "Smelling Salts"
MiracleHerb = "Miracle Herb"
Map1 = "Map 1"
Map2 = "Map 2"
GlassArmor = "Glass Armor"

# flag codes

TrialOfStrength = "Complete Trial of Strength"
TrialOfCourage = "Complete Trial of Courage"
TrialOfTruth = "Complete Trial of Truth"
TrialOfWisdom = "Complete Trial of Wisdom"

Gila = "Meet Gila"
Dai = "Meet Dai"
Jessa = "Meet Jessa"

EnterLab3 = "Enter Labyrinth L3"

KaiserKrab = "Defeat Kaiser Krab"
Tortolyde = "Defeat Tortolyde"
Doppler = "Defeat Doppler"
ShellBeast = "Defeat Shell Beast"
DarkKnight = "Defeat Dark Knight"
DarkSol = "Defeat Dark Sol"


def gold(amount: int):
    return f"{amount}g"
